services:
  privatebin:
    container_name: ${PRIVATEBIN_CONTAINER_NAME}
    image: ${PRIVATEBIN_IMAGE_NAME}:${PRIVATEBIN_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    read_only: true
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${PRIVATEBIN_HTTP_PORT}:8080
    volumes:
      - './data:/srv/data'
      - './config/conf.php:/srv/cfg/cfg.php:ro'
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

networks:
  default:
    name: ${PRIVATEBIN_CONTAINER_NAME}_network
    driver: bridge

volumes:
  default:
    name: ${PRIVATEBIN_CONTAINER_NAME}_data
    driver: local