version: "3.9"
services:
  app:
    image: privatebin/nginx-fpm-alpine:latest
    container_name: privatebin
    restart: always
    read_only: true
    ports:
      - $APP_PORT:8080
    networks:
      - default
    volumes:
      - './data:/srv/data'
      - './config/conf.php:/srv/cfg/conf.php:ro'

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local

